// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_service.proto

package com.sunego.commerce.grpc.study.dto;

public final class DemosService {
  private DemosService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022demo_service.proto\022&com.sunego.commerc" +
      "e.grpc.study.service\032\026demo_service_dto.p" +
      "roto2\361\001\n\013DemoService\022k\n\004Ping\022/.com.suneg" +
      "o.commerce.grpc.study.dto.PingRequest\0320." +
      "com.sunego.commerce.grpc.study.dto.PingR" +
      "esponse\"\000\022u\n\rgetPersonList\0222.com.sunego." +
      "commerce.grpc.study.dto.QueryParameter\032." +
      ".com.sunego.commerce.grpc.study.dto.Pers" +
      "onList\"\000B4\n\"com.sunego.commerce.grpc.stu" +
      "dy.dtoB\014DemosServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sunego.commerce.grpc.study.dto.DemoServiceDto.getDescriptor(),
        }, assigner);
    com.sunego.commerce.grpc.study.dto.DemoServiceDto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
