// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_service_dto.proto

package com.sunego.commerce.grpc.study.dto;

/**
 * Protobuf type {@code com.sunego.commerce.grpc.study.dto.Person}
 */
public  final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.sunego.commerce.grpc.study.dto.Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    age_ = 0;
    name_ = "";
    sex_ = false;
    salary_ = 0D;
    childrenCount_ = 0;
  }

 
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Person(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            age_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            sex_ = input.readBool();
            break;
          }
          case 33: {

            salary_ = input.readDouble();
            break;
          }
          case 40: {

            childrenCount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_Person_descriptor;
  }

 
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sunego.commerce.grpc.study.dto.Person.class, com.sunego.commerce.grpc.study.dto.Person.Builder.class);
  }

  public static final int AGE_FIELD_NUMBER = 1;
  private int age_;
  /**
   * <code>int32 age = 1;</code>
   */
  public int getAge() {
    return age_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEX_FIELD_NUMBER = 3;
  private boolean sex_;
  /**
   * <code>bool sex = 3;</code>
   */
  public boolean getSex() {
    return sex_;
  }

  public static final int SALARY_FIELD_NUMBER = 4;
  private double salary_;
  /**
   * <code>double salary = 4;</code>
   */
  public double getSalary() {
    return salary_;
  }

  public static final int CHILDRENCOUNT_FIELD_NUMBER = 5;
  private int childrenCount_;
  /**
   * <code>int32 childrenCount = 5;</code>
   */
  public int getChildrenCount() {
    return childrenCount_;
  }

  private byte memoizedIsInitialized = -1;
 
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

 
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (age_ != 0) {
      output.writeInt32(1, age_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (sex_ != false) {
      output.writeBool(3, sex_);
    }
    if (salary_ != 0D) {
      output.writeDouble(4, salary_);
    }
    if (childrenCount_ != 0) {
      output.writeInt32(5, childrenCount_);
    }
    unknownFields.writeTo(output);
  }

 
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, age_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (sex_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, sex_);
    }
    if (salary_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, salary_);
    }
    if (childrenCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, childrenCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

 
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sunego.commerce.grpc.study.dto.Person)) {
      return super.equals(obj);
    }
    com.sunego.commerce.grpc.study.dto.Person other = (com.sunego.commerce.grpc.study.dto.Person) obj;

    boolean result = true;
    result = result && (getAge()
        == other.getAge());
    result = result && getName()
        .equals(other.getName());
    result = result && (getSex()
        == other.getSex());
    result = result && (
        java.lang.Double.doubleToLongBits(getSalary())
        == java.lang.Double.doubleToLongBits(
            other.getSalary()));
    result = result && (getChildrenCount()
        == other.getChildrenCount());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

 
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSex());
    hash = (37 * hash) + SALARY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSalary()));
    hash = (37 * hash) + CHILDRENCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getChildrenCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sunego.commerce.grpc.study.dto.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunego.commerce.grpc.study.dto.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunego.commerce.grpc.study.dto.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunego.commerce.grpc.study.dto.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunego.commerce.grpc.study.dto.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sunego.commerce.grpc.study.dto.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunego.commerce.grpc.study.dto.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

 
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sunego.commerce.grpc.study.dto.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
 
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

 
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.sunego.commerce.grpc.study.dto.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.sunego.commerce.grpc.study.dto.Person)
      com.sunego.commerce.grpc.study.dto.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_Person_descriptor;
    }

   
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sunego.commerce.grpc.study.dto.Person.class, com.sunego.commerce.grpc.study.dto.Person.Builder.class);
    }

    // Construct using com.sunego.commerce.grpc.study.dto.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
   
    public Builder clear() {
      super.clear();
      age_ = 0;

      name_ = "";

      sex_ = false;

      salary_ = 0D;

      childrenCount_ = 0;

      return this;
    }

   
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_Person_descriptor;
    }

   
    public com.sunego.commerce.grpc.study.dto.Person getDefaultInstanceForType() {
      return com.sunego.commerce.grpc.study.dto.Person.getDefaultInstance();
    }

   
    public com.sunego.commerce.grpc.study.dto.Person build() {
      com.sunego.commerce.grpc.study.dto.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

   
    public com.sunego.commerce.grpc.study.dto.Person buildPartial() {
      com.sunego.commerce.grpc.study.dto.Person result = new com.sunego.commerce.grpc.study.dto.Person(this);
      result.age_ = age_;
      result.name_ = name_;
      result.sex_ = sex_;
      result.salary_ = salary_;
      result.childrenCount_ = childrenCount_;
      onBuilt();
      return result;
    }

   
    public Builder clone() {
      return (Builder) super.clone();
    }
   
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
   
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
   
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
   
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
   
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
   
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sunego.commerce.grpc.study.dto.Person) {
        return mergeFrom((com.sunego.commerce.grpc.study.dto.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sunego.commerce.grpc.study.dto.Person other) {
      if (other == com.sunego.commerce.grpc.study.dto.Person.getDefaultInstance()) return this;
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getSex() != false) {
        setSex(other.getSex());
      }
      if (other.getSalary() != 0D) {
        setSalary(other.getSalary());
      }
      if (other.getChildrenCount() != 0) {
        setChildrenCount(other.getChildrenCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

   
    public final boolean isInitialized() {
      return true;
    }

   
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sunego.commerce.grpc.study.dto.Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sunego.commerce.grpc.study.dto.Person) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 1;</code>
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 1;</code>
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 1;</code>
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private boolean sex_ ;
    /**
     * <code>bool sex = 3;</code>
     */
    public boolean getSex() {
      return sex_;
    }
    /**
     * <code>bool sex = 3;</code>
     */
    public Builder setSex(boolean value) {
      
      sex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool sex = 3;</code>
     */
    public Builder clearSex() {
      
      sex_ = false;
      onChanged();
      return this;
    }

    private double salary_ ;
    /**
     * <code>double salary = 4;</code>
     */
    public double getSalary() {
      return salary_;
    }
    /**
     * <code>double salary = 4;</code>
     */
    public Builder setSalary(double value) {
      
      salary_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double salary = 4;</code>
     */
    public Builder clearSalary() {
      
      salary_ = 0D;
      onChanged();
      return this;
    }

    private int childrenCount_ ;
    /**
     * <code>int32 childrenCount = 5;</code>
     */
    public int getChildrenCount() {
      return childrenCount_;
    }
    /**
     * <code>int32 childrenCount = 5;</code>
     */
    public Builder setChildrenCount(int value) {
      
      childrenCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 childrenCount = 5;</code>
     */
    public Builder clearChildrenCount() {
      
      childrenCount_ = 0;
      onChanged();
      return this;
    }
   
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

   
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.sunego.commerce.grpc.study.dto.Person)
  }

  // @@protoc_insertion_point(class_scope:com.sunego.commerce.grpc.study.dto.Person)
  private static final com.sunego.commerce.grpc.study.dto.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sunego.commerce.grpc.study.dto.Person();
  }

  public static com.sunego.commerce.grpc.study.dto.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
   
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Person(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

 
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

 
  public com.sunego.commerce.grpc.study.dto.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

