// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_service_dto.proto

package com.sunego.commerce.grpc.study.dto;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sunego.commerce.grpc.study.dto.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool sex = 3;</code>
   */
  boolean getSex();

  /**
   * <code>double salary = 4;</code>
   */
  double getSalary();

  /**
   * <code>int32 childrenCount = 5;</code>
   */
  int getChildrenCount();
}
