// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_service_dto.proto

package com.sunego.commerce.grpc.study.dto;

/**
 * Protobuf type {@code com.sunego.commerce.grpc.study.dto.PingResponse}
 */
public  final class PingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.sunego.commerce.grpc.study.dto.PingResponse)
    PingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PingResponse.newBuilder() to construct.
  private PingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PingResponse() {
    out_ = "";
  }

 
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            out_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_PingResponse_descriptor;
  }

 
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_PingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sunego.commerce.grpc.study.dto.PingResponse.class, com.sunego.commerce.grpc.study.dto.PingResponse.Builder.class);
  }

  public static final int OUT_FIELD_NUMBER = 1;
  private volatile java.lang.Object out_;
  /**
   * <code>string out = 1;</code>
   */
  public java.lang.String getOut() {
    java.lang.Object ref = out_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      out_ = s;
      return s;
    }
  }
  /**
   * <code>string out = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOutBytes() {
    java.lang.Object ref = out_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      out_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
 
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

 
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOutBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, out_);
    }
    unknownFields.writeTo(output);
  }

 
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOutBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, out_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

 
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sunego.commerce.grpc.study.dto.PingResponse)) {
      return super.equals(obj);
    }
    com.sunego.commerce.grpc.study.dto.PingResponse other = (com.sunego.commerce.grpc.study.dto.PingResponse) obj;

    boolean result = true;
    result = result && getOut()
        .equals(other.getOut());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

 
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OUT_FIELD_NUMBER;
    hash = (53 * hash) + getOut().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sunego.commerce.grpc.study.dto.PingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunego.commerce.grpc.study.dto.PingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.PingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunego.commerce.grpc.study.dto.PingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.PingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunego.commerce.grpc.study.dto.PingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.PingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunego.commerce.grpc.study.dto.PingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.PingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sunego.commerce.grpc.study.dto.PingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.PingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunego.commerce.grpc.study.dto.PingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

 
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sunego.commerce.grpc.study.dto.PingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
 
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

 
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.sunego.commerce.grpc.study.dto.PingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.sunego.commerce.grpc.study.dto.PingResponse)
      com.sunego.commerce.grpc.study.dto.PingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_PingResponse_descriptor;
    }

   
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_PingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sunego.commerce.grpc.study.dto.PingResponse.class, com.sunego.commerce.grpc.study.dto.PingResponse.Builder.class);
    }

    // Construct using com.sunego.commerce.grpc.study.dto.PingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
   
    public Builder clear() {
      super.clear();
      out_ = "";

      return this;
    }

   
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_PingResponse_descriptor;
    }

   
    public com.sunego.commerce.grpc.study.dto.PingResponse getDefaultInstanceForType() {
      return com.sunego.commerce.grpc.study.dto.PingResponse.getDefaultInstance();
    }

   
    public com.sunego.commerce.grpc.study.dto.PingResponse build() {
      com.sunego.commerce.grpc.study.dto.PingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

   
    public com.sunego.commerce.grpc.study.dto.PingResponse buildPartial() {
      com.sunego.commerce.grpc.study.dto.PingResponse result = new com.sunego.commerce.grpc.study.dto.PingResponse(this);
      result.out_ = out_;
      onBuilt();
      return result;
    }

   
    public Builder clone() {
      return (Builder) super.clone();
    }
   
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
   
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
   
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
   
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
   
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
   
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sunego.commerce.grpc.study.dto.PingResponse) {
        return mergeFrom((com.sunego.commerce.grpc.study.dto.PingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sunego.commerce.grpc.study.dto.PingResponse other) {
      if (other == com.sunego.commerce.grpc.study.dto.PingResponse.getDefaultInstance()) return this;
      if (!other.getOut().isEmpty()) {
        out_ = other.out_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

   
    public final boolean isInitialized() {
      return true;
    }

   
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sunego.commerce.grpc.study.dto.PingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sunego.commerce.grpc.study.dto.PingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object out_ = "";
    /**
     * <code>string out = 1;</code>
     */
    public java.lang.String getOut() {
      java.lang.Object ref = out_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        out_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string out = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOutBytes() {
      java.lang.Object ref = out_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        out_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string out = 1;</code>
     */
    public Builder setOut(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      out_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string out = 1;</code>
     */
    public Builder clearOut() {
      
      out_ = getDefaultInstance().getOut();
      onChanged();
      return this;
    }
    /**
     * <code>string out = 1;</code>
     */
    public Builder setOutBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      out_ = value;
      onChanged();
      return this;
    }
   
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

   
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.sunego.commerce.grpc.study.dto.PingResponse)
  }

  // @@protoc_insertion_point(class_scope:com.sunego.commerce.grpc.study.dto.PingResponse)
  private static final com.sunego.commerce.grpc.study.dto.PingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sunego.commerce.grpc.study.dto.PingResponse();
  }

  public static com.sunego.commerce.grpc.study.dto.PingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PingResponse>
      PARSER = new com.google.protobuf.AbstractParser<PingResponse>() {
   
    public PingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PingResponse> parser() {
    return PARSER;
  }

 
  public com.google.protobuf.Parser<PingResponse> getParserForType() {
    return PARSER;
  }

 
  public com.sunego.commerce.grpc.study.dto.PingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

