// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_service_dto.proto

package com.sunego.commerce.grpc.study.dto;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sunego.commerce.grpc.study.dto.PingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string in = 1;</code>
   */
  java.lang.String getIn();
  /**
   * <code>string in = 1;</code>
   */
  com.google.protobuf.ByteString
      getInBytes();
}
