// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_service_dto.proto

package com.sunego.commerce.grpc.study.dto;

public interface PingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sunego.commerce.grpc.study.dto.PingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string out = 1;</code>
   */
  java.lang.String getOut();
  /**
   * <code>string out = 1;</code>
   */
  com.google.protobuf.ByteString
      getOutBytes();
}
