// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_service_dto.proto

package com.sunego.commerce.grpc.study.dto;

/**
 * Protobuf type {@code com.sunego.commerce.grpc.study.dto.QueryParameter}
 */
public  final class QueryParameter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.sunego.commerce.grpc.study.dto.QueryParameter)
    QueryParameterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryParameter.newBuilder() to construct.
  private QueryParameter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryParameter() {
    ageStart_ = 0;
    ageEnd_ = 0;
  }

 
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryParameter(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            ageStart_ = input.readInt32();
            break;
          }
          case 16: {

            ageEnd_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_QueryParameter_descriptor;
  }

 
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_QueryParameter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sunego.commerce.grpc.study.dto.QueryParameter.class, com.sunego.commerce.grpc.study.dto.QueryParameter.Builder.class);
  }

  public static final int AGESTART_FIELD_NUMBER = 1;
  private int ageStart_;
  /**
   * <code>int32 ageStart = 1;</code>
   */
  public int getAgeStart() {
    return ageStart_;
  }

  public static final int AGEEND_FIELD_NUMBER = 2;
  private int ageEnd_;
  /**
   * <code>int32 ageEnd = 2;</code>
   */
  public int getAgeEnd() {
    return ageEnd_;
  }

  private byte memoizedIsInitialized = -1;
 
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

 
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ageStart_ != 0) {
      output.writeInt32(1, ageStart_);
    }
    if (ageEnd_ != 0) {
      output.writeInt32(2, ageEnd_);
    }
    unknownFields.writeTo(output);
  }

 
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ageStart_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ageStart_);
    }
    if (ageEnd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, ageEnd_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

 
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sunego.commerce.grpc.study.dto.QueryParameter)) {
      return super.equals(obj);
    }
    com.sunego.commerce.grpc.study.dto.QueryParameter other = (com.sunego.commerce.grpc.study.dto.QueryParameter) obj;

    boolean result = true;
    result = result && (getAgeStart()
        == other.getAgeStart());
    result = result && (getAgeEnd()
        == other.getAgeEnd());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

 
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGESTART_FIELD_NUMBER;
    hash = (53 * hash) + getAgeStart();
    hash = (37 * hash) + AGEEND_FIELD_NUMBER;
    hash = (53 * hash) + getAgeEnd();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sunego.commerce.grpc.study.dto.QueryParameter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

 
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sunego.commerce.grpc.study.dto.QueryParameter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
 
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

 
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.sunego.commerce.grpc.study.dto.QueryParameter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.sunego.commerce.grpc.study.dto.QueryParameter)
      com.sunego.commerce.grpc.study.dto.QueryParameterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_QueryParameter_descriptor;
    }

   
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_QueryParameter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sunego.commerce.grpc.study.dto.QueryParameter.class, com.sunego.commerce.grpc.study.dto.QueryParameter.Builder.class);
    }

    // Construct using com.sunego.commerce.grpc.study.dto.QueryParameter.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
   
    public Builder clear() {
      super.clear();
      ageStart_ = 0;

      ageEnd_ = 0;

      return this;
    }

   
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sunego.commerce.grpc.study.dto.DemoServiceDto.internal_static_com_sunego_commerce_grpc_study_dto_QueryParameter_descriptor;
    }

   
    public com.sunego.commerce.grpc.study.dto.QueryParameter getDefaultInstanceForType() {
      return com.sunego.commerce.grpc.study.dto.QueryParameter.getDefaultInstance();
    }

   
    public com.sunego.commerce.grpc.study.dto.QueryParameter build() {
      com.sunego.commerce.grpc.study.dto.QueryParameter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

   
    public com.sunego.commerce.grpc.study.dto.QueryParameter buildPartial() {
      com.sunego.commerce.grpc.study.dto.QueryParameter result = new com.sunego.commerce.grpc.study.dto.QueryParameter(this);
      result.ageStart_ = ageStart_;
      result.ageEnd_ = ageEnd_;
      onBuilt();
      return result;
    }

   
    public Builder clone() {
      return (Builder) super.clone();
    }
   
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
   
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
   
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
   
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
   
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
   
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sunego.commerce.grpc.study.dto.QueryParameter) {
        return mergeFrom((com.sunego.commerce.grpc.study.dto.QueryParameter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sunego.commerce.grpc.study.dto.QueryParameter other) {
      if (other == com.sunego.commerce.grpc.study.dto.QueryParameter.getDefaultInstance()) return this;
      if (other.getAgeStart() != 0) {
        setAgeStart(other.getAgeStart());
      }
      if (other.getAgeEnd() != 0) {
        setAgeEnd(other.getAgeEnd());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

   
    public final boolean isInitialized() {
      return true;
    }

   
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sunego.commerce.grpc.study.dto.QueryParameter parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sunego.commerce.grpc.study.dto.QueryParameter) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int ageStart_ ;
    /**
     * <code>int32 ageStart = 1;</code>
     */
    public int getAgeStart() {
      return ageStart_;
    }
    /**
     * <code>int32 ageStart = 1;</code>
     */
    public Builder setAgeStart(int value) {
      
      ageStart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ageStart = 1;</code>
     */
    public Builder clearAgeStart() {
      
      ageStart_ = 0;
      onChanged();
      return this;
    }

    private int ageEnd_ ;
    /**
     * <code>int32 ageEnd = 2;</code>
     */
    public int getAgeEnd() {
      return ageEnd_;
    }
    /**
     * <code>int32 ageEnd = 2;</code>
     */
    public Builder setAgeEnd(int value) {
      
      ageEnd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ageEnd = 2;</code>
     */
    public Builder clearAgeEnd() {
      
      ageEnd_ = 0;
      onChanged();
      return this;
    }
   
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

   
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.sunego.commerce.grpc.study.dto.QueryParameter)
  }

  // @@protoc_insertion_point(class_scope:com.sunego.commerce.grpc.study.dto.QueryParameter)
  private static final com.sunego.commerce.grpc.study.dto.QueryParameter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sunego.commerce.grpc.study.dto.QueryParameter();
  }

  public static com.sunego.commerce.grpc.study.dto.QueryParameter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryParameter>
      PARSER = new com.google.protobuf.AbstractParser<QueryParameter>() {
   
    public QueryParameter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryParameter(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryParameter> parser() {
    return PARSER;
  }

 
  public com.google.protobuf.Parser<QueryParameter> getParserForType() {
    return PARSER;
  }

 
  public com.sunego.commerce.grpc.study.dto.QueryParameter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

