// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_service_dto.proto

package com.sunego.commerce.grpc.study.dto;

public interface QueryParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sunego.commerce.grpc.study.dto.QueryParameter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ageStart = 1;</code>
   */
  int getAgeStart();

  /**
   * <code>int32 ageEnd = 2;</code>
   */
  int getAgeEnd();
}
